tools:
  - name: print
    cmd: echo
    args_extra:
      text: $TEXT

  - name: print_newline
    cmd:
      windows: echo.
      linux: echo

  - name: print_filename
    cmd:
      windows: echo.$FILE
      linux: echo "$FILE"

  - name: print_filename_separated
    cmd:
      windows: "echo -------------------- & echo File: $FILE & echo --------------------"
      linux: 'echo --------------------; echo "File: $FILE"; echo --------------------'

  - name: mkdir
    cmd:
      windows: cmd /X /C md
      linux: mkdir -p
    args_extra:
      dir: '"${PATH:$DIR}"'
    allow_fail: yes

  - name: rm
    cmd:
      windows: del /F /Q
      linux: rm -f
    args_extra:
      path: '"${PATH:$PATH}"'
    allow_fail: yes

  - name: rmdir
    cmd:
      windows: del /F /Q /S
      linux: rm -f -r
    args_extra:
      path: '"${PATH:$PATH}"'
    allow_fail: yes

  - name: regripper
    cmd:
      windows: '"${PATH:$DIR_REGRIPPER/rip.exe}"'
      linux: regripper
    args: -r "$FILE"
    args_extra:
      plugin: -p $PLUGIN
      profile: -f $PROFILE
      all: -a
      all_tln: -aT

  - name: srum_dump
    cmd:
      windows: '"${PATH:$DIR_SRUM_DUMP/srum_dump2.exe}"'
      linux: python3 "$DIR_SRUM_DUMP/srum_dump2.py"
    args: -i "$FILE"
    args_extra:
      reg_hive: --REG_HIVE "$REG_HIVE"
      xlsx_outfile: --XLSX_OUTFILE "$XLSX_OUTFILE"
      xlsx_template: --XLSX_TEMPLATE "$XLSX_TEMPLATE"

  - name: evtx_dump
    cmd:
      windows: '"${PATH:$DIR_EVTX_DUMP/evtx_dump.exe}"'
      linux: evtx_dump
    args: '"$FILE"'
    args_extra:
      format: --format $FORMAT
      output: --output "$OUTPUT" --no-confirm-overwrite
      events: --events $EVENTS

directories:
  regripper: ../tools/RegRipper3.0
  srum_dump: ../tools/srum-dump
  evtx_dump: ../tools
