tools:
  - name: regripper
    cmd:
      windows: $DIR_REGRIPPER/rip.exe
      linux: $DIR_REGRIPPER/regripper
    args: -r $FILE
    args_extra:
      plugin: -p $PLUGIN
      profile: -f $PROFILE
      auto: -a
  - name: srum_dump
    cmd:
      windows: $DIR_SRUM_DUMP/srum_dump2.exe
      linux: python3 $DIR_SRUM_DUMP/srum_dump2.py
    args: -i $FILE
    args_extra:
      reg_hive: --REG_HIVE $REG_HIVE
      xlsx_outfile: --XLSX_OUTFILE $XLSX_OUTFILE
      xlsx_template: --XLSX_TEMPLATE $XLSX_TEMPLATE
  - name: test_enabled_yes
    cmd: echo 'Test enabled YES - $FILE'
    enabled: yes
  - name: test_enabled_no
    cmd: echo 'Test enabled NO - $FILE'
    enabled: no
  - name: test_disabled_yes
    cmd: echo 'Test disabled YES - $FILE'
    disabled: yes
  - name: test_disabled_no
    cmd: echo 'Test disabled NO - $FILE'
    disabled: no

directories:
  regripper: /usr/bin
  srum_dump: /opt/srum-dump
